const std = @import("std");

// Import the Libretro core header definitions.
const retro = @cImport({
    @cInclude("libretro.h");
});

// Import glsym (OpenGL symbol resolver wrapper used heavily by Libretro cores).
const gl = @cImport({
    @cInclude("glsym/glsym.h");
});

// ============================================================================
// Globals
// ============================================================================

// Libretro callback pointers provided by the frontend (RetroArch) during init.
var environ_cb: retro.retro_environment_t = null;
var video_cb: retro.retro_video_refresh_t = null;
var input_poll_cb: retro.retro_input_poll_t = null;

// Configuration and state structure for OpenGL context negotiation.
var hw_render: retro.retro_hw_render_callback = undefined;

// ============================================================================
// Core Libretro Implementation
// ============================================================================

// Returns the Libretro API version matching the header definitions.
export fn retro_api_version() callconv(.c) c_uint {
    return retro.RETRO_API_VERSION;
}

// Populates core metadata including name, version, and supported file extensions.
export fn retro_get_system_info(info: *retro.retro_system_info) callconv(.c) void {
    info.* = .{
        .library_name = "Zig Square Test",
        .library_version = "0.2",
        .valid_extensions = null, // null indicates no ROM files are needed.
        .need_fullpath = false,
        .block_extract = false,
    };
}

// Defines video constraints (dimensions, aspect ratio) and targeted frame rates.
export fn retro_get_system_av_info(info: *retro.retro_system_av_info) callconv(.c) void {
    info.* = .{
        .geometry = .{
            .base_width = 640,
            .base_height = 480,
            .max_width = 640,
            .max_height = 480,
            .aspect_ratio = 4.0 / 3.0,
        },
        .timing = .{
            .fps = 60.0,
            .sample_rate = 0.0, // No audio generated by this core.
        },
    };
}

// Frontend invokes this to provide the core with its primary environmental callback.
export fn retro_set_environment(cb: retro.retro_environment_t) callconv(.c) void {
    environ_cb = cb;
    if (cb) |c| {
        var no_rom = true;
        // Inform RetroArch that this core can boot immediately without loading a ROM file.
        _ = c(retro.RETRO_ENVIRONMENT_SET_SUPPORT_NO_GAME, &no_rom);
    }
}

// Callback updates for frame delivery.
export fn retro_set_video_refresh(cb: retro.retro_video_refresh_t) callconv(.c) void {
    video_cb = cb;
}

// Callback updates for processing controller state requests.
export fn retro_set_input_poll(cb: retro.retro_input_poll_t) callconv(.c) void {
    input_poll_cb = cb;
}

// Unused structural audio/input callbacks mandatory for interface compliance.
export fn retro_set_audio_sample(cb: retro.retro_audio_sample_t) callconv(.c) void {
    _ = cb;
}
export fn retro_set_audio_sample_batch(cb: retro.retro_audio_sample_batch_t) callconv(.c) void {
    _ = cb;
}
export fn retro_set_input_state(cb: retro.retro_input_state_t) callconv(.c) void {
    _ = cb;
}

// Triggered by RetroArch when the graphics context is generated or reset.
fn context_reset() callconv(.c) void {
    std.log.info("Context Reset - Initializing glsym", .{});

    // Resolve specific OpenGL dynamic function pointers through glsym layout.
    if (hw_render.get_proc_address) |get_proc| {
        gl.rglgen_resolve_symbols(get_proc);
    } else {
        std.log.err("glsym critical error: get_proc_address is null!", .{});
    }
}

// Triggered by RetroArch when tearing down the context (e.g., core shutdown/resolution swap).
fn context_destroy() callconv(.c) void {
    std.log.info("Context Destroyed", .{});
}

// Invoked when game loop initialization occurs. Here we request Hardware Acceleration.
export fn retro_load_game(game: ?*const retro.retro_game_info) callconv(.c) bool {
    _ = game;

    // Define OpenGL parameters requested by the core.
    hw_render = .{
        .context_type = retro.RETRO_HW_CONTEXT_OPENGL,
        .context_reset = context_reset,
        .context_destroy = context_destroy,
        .get_current_framebuffer = null, // RetroArch populates this dynamically on return.
        .get_proc_address = null, // RetroArch populates this dynamically on return.
        .depth = true,
        .stencil = false,
        .bottom_left_origin = true,
        .version_major = 2, // Request legacy OpenGL 2.1 environment.
        .version_minor = 1,
        .cache_context = false,
        .debug_context = false,
    };

    // Negotiate hardware context settings handshake with the frontend.
    if (environ_cb) |cb| {
        if (!cb(retro.RETRO_ENVIRONMENT_SET_HW_RENDER, &hw_render)) {
            std.log.err("Frontend failed to accept hardware rendering settings.", .{});
            return false;
        }
    }
    return true;
}

// Standard main frame loop executed roughly 60 times per second.
export fn retro_run() callconv(.c) void {
    // Poll active input hardware states.
    if (input_poll_cb) |poll| poll();

    // REQUIREMENT 1: Query and target the internal frame buffer provided by RetroArch.
    if (hw_render.get_current_framebuffer) |get_fbo| {
        const fbo_id = get_fbo();
        // Route calls using gl prefix wrapper to address correct glsym tables.
        gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, @intCast(fbo_id));
    }

    // Set view scale viewport matching geometry resolution.
    gl.glViewport(0, 0, 640, 480);

    // Render a deep blue background layout.
    gl.glClearColor(0.1, 0.1, 0.2, 1.0);
    gl.glClear(gl.GL_COLOR_BUFFER_BIT | gl.GL_DEPTH_BUFFER_BIT);

    // Draw an orange quad centered in the middle of clip space.
    gl.glBegin(gl.GL_QUADS);
    gl.glColor3f(1.0, 0.5, 0.0);

    gl.glVertex2f(-0.5, -0.5);
    gl.glVertex2f(0.5, -0.5);
    gl.glVertex2f(0.5, 0.5);
    gl.glVertex2f(-0.5, 0.5);

    gl.glEnd();

    // REQUIREMENT 2: Inform RetroArch that the hardware framebuffer is fully drawn.
    // Instead of passing a raw pointer to pixels, pass RETRO_HW_FRAME_BUFFER_VALID.
    if (video_cb) |vcb| {
        vcb(retro.RETRO_HW_FRAME_BUFFER_VALID, 640, 480, 0);
    }
}

// ============================================================================
// Mandatory Libretro Structural Boilerplate
// ============================================================================
export fn retro_init() callconv(.c) void {}
export fn retro_deinit() callconv(.c) void {}
export fn retro_reset() callconv(.c) void {}
export fn retro_unload_game() callconv(.c) void {}

export fn retro_set_controller_port_device(port: c_uint, device: c_uint) callconv(.c) void {
    _ = port;
    _ = device;
}
export fn retro_serialize(data: ?*anyopaque, size: usize) callconv(.c) bool {
    _ = data;
    _ = size;
    return false;
}
export fn retro_unserialize(data: ?*const anyopaque, size: usize) callconv(.c) bool {
    _ = data;
    _ = size;
    return false;
}
export fn retro_serialize_size() callconv(.c) usize {
    return 0;
}
export fn retro_cheat_reset() callconv(.c) void {}
export fn retro_cheat_set(index: c_uint, is_code: bool, code: [*:0]const u8) callconv(.c) void {
    _ = index;
    _ = is_code;
    _ = code;
}
export fn retro_load_game_special(game_type: c_uint, info: ?*const retro.retro_game_info, num_info: usize) callconv(.c) bool {
    _ = game_type;
    _ = info;
    _ = num_info;
    return false;
}
export fn retro_get_region() callconv(.c) c_uint {
    return retro.RETRO_REGION_NTSC;
}
export fn retro_get_memory_data(id: c_uint) callconv(.c) ?*anyopaque {
    _ = id;
    return null;
}
export fn retro_get_memory_size(id: c_uint) callconv(.c) usize {
    _ = id;
    return 0;
}
